## ベクトル

In [1]:
import numpy as np

In [2]:
x = np.array([-5.2,4.0,4.4]).reshape(3,1)
x

array([[-5.2],
       [ 4. ],
       [ 4.4]])

In [3]:
x.T

array([[-5.2,  4. ,  4.4]])

## ベクトルの基本演算

In [1]:
import numpy as np

In [4]:
x = np.array([2,1]).reshape(2,1)
y = np.array([1,3]).reshape(2,1)
print(x)
print(y)

[[2]
 [1]]
[[1]
 [3]]


In [5]:
x + y

array([[3],
       [4]])

In [6]:
x - y

array([[ 1],
       [-2]])

In [8]:
np.dot(x,2)

array([[4],
       [2]])

In [9]:
np.dot(y,-1)

array([[-1],
       [-3]])

In [9]:
x = np.arange(0,20,5)
print(x)

[ 0  5 10 15]


In [5]:
x = np.arange(1,10).reshape(-1,1)
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## ベクトルの分解と線形結合

In [20]:
import numpy as np

In [21]:
x = np.array([2,1]).reshape(-1,1)
x

array([[2],
       [1]])

In [22]:
e = x / np.linalg.norm(x)
e

array([[0.89442719],
       [0.4472136 ]])

In [23]:
np.linalg.norm(e)

0.9999999999999999

In [24]:
round(np.linalg.norm(e),10)

1.0

## ノルム、距離、内積

In [25]:
import numpy as np

In [26]:
x = np.array([4,-3]).reshape(-1,1)
x

array([[ 4],
       [-3]])

In [28]:
np.linalg.norm(x)

5.0

In [29]:
np.linalg.norm(x,1)

7.0

In [30]:
np.linalg.norm(x,2)

5.0

In [31]:
np.linalg.norm(x,np.inf)

4.0

In [32]:
x = np.array([4,-3]).reshape(-1,1)
y = np.array([2,4]).reshape(-1,1)
np.linalg.norm(x - y)

7.280109889280518

In [33]:
from scipy.spatial import distance
distance.euclidean(x,y)

7.280109889280518

In [34]:
distance.cityblock(x,y)

9

In [35]:
distance.chebyshev(x,y)

7

In [36]:
np.dot(x.T,y)

array([[-4]])

In [37]:
np.dot(x.T,y)[0,0]

-4

In [38]:
def cos_similarity(x,y):
    return np.dot(x.T,y)[0,0] / (np.linalg.norm(x) * np.linalg.norm(y))

In [39]:
x = np.array([4,-3]).reshape(-1,1)
y = np.array([2,4]).reshape(-1,1)

In [40]:
cos_similarity(x,y)

-0.17888543819998318

In [43]:
o = np.array([255,165,0]).reshape(-1,1)
r = np.array([255,0,0]).reshape(-1,1)
y = np.array([255,255,0]).reshape(-1,1)
b = np.array([0,0,255]).reshape(-1,1)

In [44]:
distance.euclidean(o,o)

0.0

In [45]:
distance.euclidean(o,r)

165.0

In [46]:
distance.euclidean(o,y)

90.0

In [47]:
distance.euclidean(o,b)

396.57912199206856

In [48]:
cos_similarity(o,o)

1.0

In [49]:
cos_similarity(o,r)

0.8395701571521511

In [50]:
cos_similarity(o,y)

0.9778024140774094

In [51]:
cos_similarity(o,b)

0.0

## 正規直交基底

In [52]:
import numpy as np

In [53]:
a1 = np.array([1,-1,1]).reshape(-1,1)
a2 = np.array([0,2,1]).reshape(-1,1)
a3 = np.array([2,1,1]).reshape(-1,1)

In [54]:
A = np.concatenate((a1,np.concatenate((a2,a3),axis=1)),axis=1)
A

array([[ 1,  0,  2],
       [-1,  2,  1],
       [ 1,  1,  1]])

In [55]:
A = np.array(A,dtype=np.float64)
A

array([[ 1.,  0.,  2.],
       [-1.,  2.,  1.],
       [ 1.,  1.,  1.]])

In [57]:
N = A.shape[1]
N

3

In [58]:
u = A[:,0].reshape(-1,1) / np.linalg.norm(A[:,0])
u

array([[ 0.57735027],
       [-0.57735027],
       [ 0.57735027]])

In [59]:
for k in range(1,N):
    b = A[:,k].reshape(-1,1)
    for j in range(k):
        b = b - np.dot(u[:,j].reshape(-1,1).T,A[:,k].reshape(-1,1)) * u[:,j].reshape(-1,1)
    ui = b / np.linalg.norm(b)
    u = np.append(u,ui,axis=1)
u

array([[ 0.57735027,  0.15430335,  0.80178373],
       [-0.57735027,  0.77151675,  0.26726124],
       [ 0.57735027,  0.6172134 , -0.53452248]])

In [60]:
q,r = np.linalg.qr(A)
q

array([[-0.57735027, -0.15430335, -0.80178373],
       [ 0.57735027, -0.77151675, -0.26726124],
       [-0.57735027, -0.6172134 ,  0.53452248]])

In [61]:
np.linalg.norm(q[:,0])

1.0

In [62]:
np.linalg.norm(q[:,1])

1.0000000000000002

In [63]:
np.linalg.norm(q[:,2])

1.0

In [64]:
np.dot(q[:,0],q[:,1])

-5.551115123125783e-17

In [65]:
np.dot(q[:,0],q[:,2])

0.0

In [66]:
np.dot(q[:,1],q[:,2])

1.942890293094024e-16