**1.4.4 Numpy入門**

In [1]:
import numpy
numpy.version.full_version

'1.20.3'

In [2]:
import numpy as np
a = np.array([0,1,2,3,4,5])
print(a)
print(a.ndim)
print(a.shape)

[0 1 2 3 4 5]
1
(6,)


In [4]:
b = a.reshape((3,2))
print(b)
print(b.ndim)
print(b.shape)

[[0 1]
 [2 3]
 [4 5]]
2
(3, 2)


In [6]:
b[1][0] = 77
print(b)
print(a)

[[ 0  1]
 [77  3]
 [ 4  5]]
[ 0  1 77  3  4  5]


In [7]:
c = a.reshape((3,2)).copy()
c

array([[ 0,  1],
       [77,  3],
       [ 4,  5]])

In [8]:
c[0][0] = -99
print(c)
print(a)

[[-99   1]
 [ 77   3]
 [  4   5]]
[ 0  1 77  3  4  5]


In [9]:
print(a*2)

[  0   2 154   6   8  10]


In [10]:
print(a ** 2)

[   0    1 5929    9   16   25]


In [11]:
[1,2,3,4,5] * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [12]:
[1,2,3,4,5] ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [13]:
a[np.array([2,3,4])]

array([77,  3,  4])

In [14]:
a>4

array([False, False,  True, False, False,  True])

In [15]:
a[a>4]

array([77,  5])

In [17]:
a[a>4] = 4
a

array([0, 1, 4, 3, 4, 4])

In [18]:
a

array([0, 1, 4, 3, 4, 4])

In [20]:
a.clip(1,5)

array([1, 1, 4, 3, 4, 4])

In [21]:
c = np.array([1,2,np.NAN,3,4])
c

array([ 1.,  2., nan,  3.,  4.])

In [22]:
np.isnan(c)

array([False, False,  True, False, False])

In [23]:
c[~np.isnan(c)]

array([1., 2., 3., 4.])

In [24]:
np.mean(c[~np.isnan(c)])

2.5